### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [joshuawolfsohn/Private-DNS-Quick-Tile#4]
strip DOS endlines please: https://github.com/joshuawolfsohn/Private-DNS-Quick-Tile/blob/master/gradle/wrapper/gradle-wrapper.properties

**Comment by joshuawolfsohn** [comment]
Fixed with latest release at tag v1.5.1. Let me know here if you find any other issues with the F-Droid build, otherwise I'll close this issue once the new build is available on F-Droid. Thank you :)

**Comment by szechp** [comment]
F-droid still doesn't offer the latest version, it still only shows 1.4.5

**Comment by licaon-kter** [comment]
@joshuawolfsohn if you just Tag without actually incrementing... There's no new version.

Fix https://github.com/joshuawolfsohn/Private-DNS-Quick-Tile/blob/master/app/build.gradle#L9 and delete & retag v1.5.1

**Comment by joshuawolfsohn** [comment]
@licaon-kter 

I deleted v1.5.1 and v1.5, and I retagged the latest version to be v1.5 now. Thank you very much for the help!

**Comment by szechp** [comment]
Hey, f-droid ist still not building the latest version 🤷🏼‍♂️

**Comment by licaon-kter** [comment]
1.5 is disabled in the metadata...yes...I said `1.5.1` for a reason...

**Comment by licaon-kter** [comment]
nvm, https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6991 

1.5 it is
